### ISSUE TITLE
Upgade API/impl

### ISSUE THREAD

**Issue by JohnKhandygo** [RomaSV/TrainingProject#5]
- [ ] Конструктор из строки https://github.com/RomaSV/TrainingProject/blob/f1555cd3455e111173a6f0d535b0b2d879e18130/src/task1/BigUnsignedInt.java#L9 реализован некорректно.
- [ ] Внутри метода https://github.com/RomaSV/TrainingProject/blob/f1555cd3455e111173a6f0d535b0b2d879e18130/src/task1/BigUnsignedInt.java#L16 операция `normalizedValue` используется неэффективно.
- [ ] Метод https://github.com/RomaSV/TrainingProject/blob/f1555cd3455e111173a6f0d535b0b2d879e18130/src/task1/BigUnsignedInt.java#L39 реализован некорректно, поскольку допускается наличие лидирующих нулей в числе.

**Comment by RomaSV** [comment]
Исправлено.
