### ISSUE TITLE
Task 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [RomaSV/TrainingProject#7]
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**Задача**

Вывод на консоль указанного (в аргументе командной строки) текстового файла с фильтрацией:
word задаёт слово для поиска (на консоль выводятся только содержащие его строки)
-r (regex) вместо слова задаёт регулярное выражение для поиска (на консоль выводятся только строки, содержащие данное выражение)
-v инвертирует условие фильтрации (выводится только то, что ему НЕ соответствует)
-i игнорировать регистр слов

Command Line: grep [-v] [-i] [-r] word inputname.txt

Кроме самой программы, следует написать автоматические тесты к ней.

**P.S.** К сожалению, не удалось посидеть и придумать для Вас по-настоящему интересную задачу. Если Вас это устроит, то мы можем потом дополнить условие этой задачи.

**Comment by JohnKhandygo** [comment]
- [ ] Некорректно реализована обработка опции `-r`. 
- [ ] Не понял, почему нельзя использовать `-r` вместе с `-i` и/или `-v`.
- [ ] Тесты не покрывают парсинг аргументов командной строки.
- [ ] Тесты не покрывают исключительные ситуации.
- [ ] В тестах много boilerplate code, связанного с созданием и закрытием reader'ов. Согласитесь, было бы намного удобнее, если бы этот код не приходилось писать каждый раз. И тесты станут чище. 
- [ ] Вообще в тестах немножко бардак. Попробуйте более точно придерживаться концепции [given - when - than](https://martinfowler.com/bliki/GivenWhenThen.html) и помните, что каждый тест в идеале должен проверять что-то "одно".
- [ ] Мне бы хотелось увидеть какой-нибудь скрипт (в идеале bash), используя который можно было бы легко запустить собранный артефакт из терминала. 
- [ ] Если бы я захотел использовать Вашу программу как библиотеку, мне пришлось бы каждый раз разбивать результат обратно на строки. 
- [ ] Если бы я захотел использовать Вашу программу как библиотеку, мне было бы не очень удобно каждый раз пробрасывать все эти булевы параметры. Просто потому, что, когда аргументов слишком много (больше 3 - 4), приходится постоянно подглядывать в javadoc, чтобы понять, что зачем нужно.

**Comment by RomaSV** [comment]
Исравил.
Только пока не разобрался, как собирать jar с помощью maven, поэтому скрипт будет позже (наверно это очень просто, но туплю).

**Comment by JohnKhandygo** [comment]
Нам с Вами надо обсудить третье задание. Планируете завтра на паре быть?

**Comment by RomaSV** [comment]
Да
